#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Global TopBar Search
# Spec: 003-global-topbar-search

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PROJECT SETUP
# ============================================

echo ""
echo "Project: CallVault - Global TopBar Search Feature"
echo "Service: Frontend (React + TypeScript + Vite)"
echo ""

# Check if we're in the project root
if [ ! -f "package.json" ]; then
    echo -e "${RED}Error: package.json not found. Please run from project root.${NC}"
    exit 1
fi

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting development server..."
echo ""

# Start Vite development server
npm run dev &
VITE_PID=$!

# Wait for Vite to be ready
wait_for_service 3000 "Vite Development Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Development Notes:"
echo "  - Search feature will be built across 5 phases"
echo "  - Phase 1: Foundation (types, stores)"
echo "  - Phase 2: Search Logic (hooks, queries)"
echo "  - Phase 3: UI Components (modal, results)"
echo "  - Phase 4: Integration (TopBar, navigation)"
echo "  - Phase 5: Validation (tests, performance)"
echo ""
echo "To stop services: Ctrl+C or kill $VITE_PID"
echo ""
echo "========================================"
