/**
 * Invitations Service (Phase 16 — WKSP-10/11)
 *
 * Service layer for workspace_invitations table operations.
 * Handles creating, revoking, resending, and accepting workspace invitations.
 *
 * NOTE on email delivery: The project has no email sending infrastructure
 * (no Resend, no Mailgun) as of Phase 16. Creating an invitation generates
 * the DB record and produces a shareable link. Email delivery is deferred
 * to Phase 17+ or via Supabase webhooks.
 */

import { supabase } from '@/integrations/supabase/client'
import type { WorkspaceInvitation, WorkspaceInviteDetails } from '@/types/workspace'

/**
 * Fetches all pending invitations for a workspace.
 * Returns invitations with status = 'pending' (not accepted, revoked, or expired).
 */
export async function getInvitations(workspaceId: string): Promise<WorkspaceInvitation[]> {
  const { data, error } = await supabase
    .from('workspace_invitations')
    .select('id, workspace_id, invited_by, email, role, token, status, expires_at, created_at, accepted_at')
    .eq('workspace_id', workspaceId)
    .eq('status', 'pending')
    .order('created_at', { ascending: false })

  if (error) {
    throw new Error(`Failed to fetch invitations: ${error.message}`)
  }

  return (data ?? []) as WorkspaceInvitation[]
}

/**
 * Creates a new workspace invitation.
 * Token is auto-generated by the DB default (gen_random_uuid()::text or similar).
 * Returns the created invitation with its token for generating the shareable link.
 */
export async function createInvitation(
  workspaceId: string,
  invitedBy: string,
  email: string,
  role: WorkspaceInvitation['role']
): Promise<WorkspaceInvitation> {
  const { data, error } = await supabase
    .from('workspace_invitations')
    .insert({
      workspace_id: workspaceId,
      invited_by: invitedBy,
      email,
      role,
    })
    .select('id, workspace_id, invited_by, email, role, token, status, expires_at, created_at, accepted_at')
    .single()

  if (error) {
    throw new Error(`Failed to create invitation: ${error.message}`)
  }

  return data as WorkspaceInvitation
}

/**
 * Revokes a pending invitation by setting its status to 'revoked'.
 * Revoked invitations cannot be accepted.
 */
export async function revokeInvitation(invitationId: string): Promise<void> {
  const { error } = await supabase
    .from('workspace_invitations')
    .update({ status: 'revoked' })
    .eq('id', invitationId)

  if (error) {
    throw new Error(`Failed to revoke invitation: ${error.message}`)
  }
}

/**
 * Refreshes the expiry of a pending invitation by extending it 7 days from now.
 * Email re-send is a future concern — for now, just refresh the expiry window.
 */
export async function resendInvitation(invitationId: string): Promise<void> {
  const newExpiry = new Date()
  newExpiry.setDate(newExpiry.getDate() + 7)

  const { error } = await supabase
    .from('workspace_invitations')
    .update({ expires_at: newExpiry.toISOString() })
    .eq('id', invitationId)

  if (error) {
    throw new Error(`Failed to resend invitation: ${error.message}`)
  }
}

/**
 * Fetches invite details by token using the get_workspace_invite_details RPC.
 * Called from the join page to show context before the user accepts.
 * Returns workspace name, org name, inviter name, role, and expiry.
 */
export async function getInviteDetails(token: string): Promise<WorkspaceInviteDetails> {
  const { data, error } = await supabase.rpc('get_workspace_invite_details', { p_token: token })

  if (error) {
    throw new Error(`Failed to get invite details: ${error.message}`)
  }

  if (!data) {
    throw new Error('Invitation not found or has expired')
  }

  // RPC returns an array; take the first row
  const result = Array.isArray(data) ? data[0] : data

  if (!result) {
    throw new Error('Invitation not found or has expired')
  }

  return result as WorkspaceInviteDetails
}

/**
 * Accepts an invitation for the given user by calling the accept_workspace_invite RPC.
 * On success, the user is added to the workspace as a member with the invite's role.
 * The invitation status is updated to 'accepted'.
 */
export async function acceptInvite(token: string, userId: string): Promise<void> {
  const { error } = await supabase.rpc('accept_workspace_invite', {
    p_token: token,
    p_user_id: userId,
  })

  if (error) {
    throw new Error(`Failed to accept invitation: ${error.message}`)
  }
}

/**
 * Generates the shareable invite link for a token.
 * Pure function — no DB call. Uses window.location.origin for the base URL.
 */
export function getShareableLink(token: string): string {
  return `${window.location.origin}/join/workspace/${token}`
}
