/**
 * Invitations Service (Phase 16 — WKSP-10/11)
 *
 * Service layer for workspace_invitations table operations.
 * Handles creating, revoking, resending, and accepting workspace invitations.
 *
 * NOTE on email delivery: The project has no email sending infrastructure
 * (no Resend, no Mailgun) as of Phase 16. Creating an invitation generates
 * the DB record and produces a shareable link. Email delivery is deferred
 * to Phase 17+ or via Supabase webhooks.
 */

import { supabase } from '@/integrations/supabase/client'
import type { WorkspaceInvitation } from '@/types/workspace'

/**
 * Creates a new workspace invitation.
 * Re-sending an existing pending invitation refreshes the same row so callers
 * get a valid token without leaking the workspace/email/status unique index.
 * Token is generated by the DB default on insert and by the client on resend.
 * Returns the created invitation with its token for generating the shareable link.
 */
export async function createInvitation(
  workspaceId: string,
  invitedBy: string,
  email: string,
  role: WorkspaceInvitation['role']
): Promise<WorkspaceInvitation> {
  const normalizedEmail = email.trim().toLowerCase()
  const existingInvite = await getPendingInvitation(workspaceId, normalizedEmail)

  if (existingInvite) {
    return refreshPendingInvitation(existingInvite.id, invitedBy, role)
  }

  const { data, error } = await supabase
    .from('workspace_invitations')
    .insert({
      workspace_id: workspaceId,
      invited_by: invitedBy,
      email: normalizedEmail,
      role,
    })
    .select('id, workspace_id, invited_by, email, role, token, status, expires_at, created_at, accepted_at')
    .single()

  if (error) {
    if (isUniqueViolation(error)) {
      const pendingInvite = await getPendingInvitation(workspaceId, normalizedEmail)
      if (pendingInvite) {
        return refreshPendingInvitation(pendingInvite.id, invitedBy, role)
      }
    }

    throw new Error(`Failed to create invitation: ${error.message}`)
  }

  return data as WorkspaceInvitation
}

async function getPendingInvitation(
  workspaceId: string,
  email: string
): Promise<WorkspaceInvitation | null> {
  const { data, error } = await supabase
    .from('workspace_invitations')
    .select('id, workspace_id, invited_by, email, role, token, status, expires_at, created_at, accepted_at')
    .eq('workspace_id', workspaceId)
    .eq('email', email)
    .eq('status', 'pending')
    .maybeSingle()

  if (error) {
    throw new Error(`Failed to check existing invitation: ${error.message}`)
  }

  return (data as WorkspaceInvitation | null) ?? null
}

async function refreshPendingInvitation(
  invitationId: string,
  invitedBy: string,
  role: WorkspaceInvitation['role']
): Promise<WorkspaceInvitation> {
  const expiresAt = new Date()
  expiresAt.setDate(expiresAt.getDate() + 7)

  const { data, error } = await supabase
    .from('workspace_invitations')
    .update({
      invited_by: invitedBy,
      role,
      token: crypto.randomUUID().replace(/-/g, ''),
      expires_at: expiresAt.toISOString(),
      accepted_at: null,
      status: 'pending',
    })
    .eq('id', invitationId)
    .select('id, workspace_id, invited_by, email, role, token, status, expires_at, created_at, accepted_at')
    .single()

  if (error) {
    throw new Error(`Failed to refresh invitation: ${error.message}`)
  }

  return data as WorkspaceInvitation
}

function isUniqueViolation(error: { code?: string; message?: string }): boolean {
  return (
    error.code === '23505' ||
    error.message?.includes('duplicate key value violates unique constraint') === true ||
    error.message?.includes('workspace_invitations_workspace_id_email_status_key') === true
  )
}

/**
 * Revokes a pending invitation by setting its status to 'revoked'.
 * Revoked invitations cannot be accepted.
 */
export async function revokeInvitation(invitationId: string): Promise<void> {
  const { error } = await supabase
    .from('workspace_invitations')
    .update({ status: 'revoked' })
    .eq('id', invitationId)

  if (error) {
    throw new Error(`Failed to revoke invitation: ${error.message}`)
  }
}

/**
 * Accepts an invitation for the given user by calling the accept_workspace_invite RPC.
 * On success, the user is added to the workspace as a member with the invite's role.
 * The invitation status is updated to 'accepted'.
 */
export async function acceptInvite(token: string, userId: string): Promise<void> {
  const { error } = await supabase.rpc('accept_workspace_invite', {
    p_token: token,
    p_user_id: userId,
  })

  if (error) {
    throw new Error(`Failed to accept invitation: ${error.message}`)
  }
}

/**
 * Generates the shareable invite link for a token.
 * Pure function — no DB call. Uses window.location.origin for the base URL.
 */
export function getShareableLink(token: string): string {
  return `${window.location.origin}/join/workspace/${token}`
}
