/**
 * MCP Tokens Service
 *
 * CRUD operations for mcp_tokens — long-lived API keys that expose a workspace
 * or organization's calls to external AI tools (Claude Desktop, Cursor, etc.).
 *
 * RLS on mcp_tokens ensures users can only access their own tokens.
 * Token values are generated server-side by Postgres (encode(gen_random_bytes(32), 'hex')).
 */

import { supabase } from '@/integrations/supabase/client'
import type { ToolCategory } from '@/lib/mcp-tool-categories'

const PUBLIC_MCP_BASE_URL = 'https://api.callvaultai.com/mcp'

// ─── Types ────────────────────────────────────────────────────────────────────

export type McpTokenScope = 'workspace' | 'organization'

export interface McpToken {
  id: string
  user_id: string
  org_id: string | null
  workspace_id: string | null
  name: string
  token: string
  scope: McpTokenScope
  last_used_at: string | null
  created_at: string
  revoked_at?: string | null
  /** Phase 23: per-token capability gating. null = legacy full-access (D-13). */
  enabled_categories: ToolCategory[] | null
}

export interface McpManualTokenConnection extends McpToken {
  connection_type: 'Manual token'
  scope_label: 'Organization' | 'Workspace'
  endpoint_url: string
  resource_url: string
  token_preview: string
  categories_summary: string
}

export interface CreateMcpTokenParams {
  name: string
  scope: McpTokenScope
  org_id: string
  /** Required when scope = 'workspace' */
  workspace_id?: string
}

// ─── Service functions ────────────────────────────────────────────────────────

/**
 * Fetch all MCP tokens for the authenticated user.
 * RLS on mcp_tokens restricts results to user_id = auth.uid().
 */
export async function getMcpTokens(): Promise<McpToken[]> {
  const { data, error } = await supabase
    .from('mcp_tokens')
    .select('id, user_id, org_id, workspace_id, name, token, scope, last_used_at, created_at, revoked_at, enabled_categories')
    .order('created_at', { ascending: false })

  if (error) {
    throw new Error(`Failed to fetch MCP tokens: ${error.message}`)
  }

  return data ?? []
}

/**
 * Count MCP tokens for a given organization.
 * Used to enforce the one-token-per-org limit before insertion.
 */
export async function getOrgTokenCount(orgId: string): Promise<number> {
  const { count, error } = await supabase
    .from('mcp_tokens')
    .select('id', { count: 'exact', head: true })
    .eq('org_id', orgId)

  if (error) {
    throw new Error(`Failed to check existing MCP tokens: ${error.message}`)
  }

  return count ?? 0
}

/**
 * Create a new MCP token.
 * The token hex value is auto-generated by Postgres default.
 * Returns the full token row including the generated token value — surface it to the user once.
 *
 * Enforces one token per organization — throws if the org already has a token.
 */
export async function createMcpToken(params: CreateMcpTokenParams): Promise<McpToken> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const existingCount = await getOrgTokenCount(params.org_id)
  if (existingCount >= 1) {
    throw new Error('This organization already has an MCP token. Delete the existing token to create a new one.')
  }

  const insert: Record<string, string | null> = {
    user_id: user.id,
    name: params.name.trim() || 'My MCP Token',
    scope: params.scope,
    org_id: params.org_id,
    workspace_id: params.scope === 'workspace' ? (params.workspace_id ?? null) : null,
  }

  const { data, error } = await supabase
    .from('mcp_tokens')
    .insert(insert)
    .select('id, user_id, org_id, workspace_id, name, token, scope, last_used_at, created_at, revoked_at, enabled_categories')
    .single()

  if (error) {
    throw new Error(`Failed to create MCP token: ${error.message}`)
  }

  return data
}

/**
 * Delete an MCP token by ID.
 * RLS ensures users can only delete their own tokens.
 */
export async function deleteMcpToken(id: string): Promise<void> {
  const { error } = await supabase
    .from('mcp_tokens')
    .delete()
    .eq('id', id)

  if (error) {
    throw new Error(`Failed to delete MCP token: ${error.message}`)
  }
}

/**
 * Regenerate an MCP token — atomically swaps the token hex value.
 * Calls the regenerate_mcp_token RPC which uses gen_random_bytes(32).
 * Preserves name, scope, org_id, workspace_id. Old token immediately stops working.
 */
export async function regenerateMcpToken(id: string): Promise<McpToken> {
  const { data, error } = await supabase
    .rpc('regenerate_mcp_token', { p_token_id: id })

  if (error) {
    throw new Error(`Failed to regenerate MCP token: ${error.message}`)
  }

  // RPC returns an array (RETURNS TABLE); take first row
  const row = Array.isArray(data) ? data[0] : data
  if (!row) {
    throw new Error('Token not found or you do not have permission to regenerate it')
  }

  return row
}

/**
 * Build the full MCP server endpoint URL for a given token value.
 * The URL is pasted into Claude Desktop / Cursor / ChatGPT config.
 *
 * Uses the vanity API domain (api.callvaultai.com/mcp) which is served by a
 * Cloudflare Worker proxy that forwards to the Supabase edge function. The
 * worker also serves OAuth metadata at /.well-known/oauth-* so MCP clients
 * discover everything from the same origin.
 *
 * Old URLs are kept working server-side for backwards compatibility, but the
 * product UI should always show the public vanity endpoint:
 *   - https://app.callvaultai.com/api/mcp (Vercel rewrite)
 *   - https://<project>.supabase.co/functions/v1/mcp-server (raw Supabase)
 */
export function getMcpUrl(): string {
  return PUBLIC_MCP_BASE_URL
}

export function buildScopedMcpUrl(scope: McpTokenScope, workspaceId: string | null): string {
  const baseUrl = getMcpUrl()
  if (scope !== 'workspace') return baseUrl
  return workspaceId ? `${baseUrl}/w/${workspaceId}` : baseUrl
}

function summarizeCategories(value: ToolCategory[] | null): string {
  const categories = value ?? ['read', 'write', 'ai', 'admin']
  return categories
    .map((category) => (category === 'ai' ? 'AI' : category.charAt(0).toUpperCase() + category.slice(1)))
    .join(', ')
}

function tokenPreview(token: string): string {
  if (token.length <= 12) return token
  return `${token.slice(0, 8)}...${token.slice(-4)}`
}

export function toManualTokenConnection(token: McpToken): McpManualTokenConnection {
  const endpointUrl = buildScopedMcpUrl(token.scope, token.workspace_id)
  return {
    ...token,
    connection_type: 'Manual token',
    scope_label: token.scope === 'workspace' ? 'Workspace' : 'Organization',
    endpoint_url: endpointUrl,
    resource_url: endpointUrl,
    token_preview: tokenPreview(token.token),
    categories_summary: summarizeCategories(token.enabled_categories),
  }
}
