/**
 * MCP Tokens Service
 *
 * CRUD operations for mcp_tokens — long-lived API keys that expose a workspace
 * or organization's calls to external AI tools (Claude Desktop, Cursor, etc.).
 *
 * RLS on mcp_tokens ensures users can only access their own tokens.
 * Token values are generated server-side by Postgres (encode(gen_random_bytes(32), 'hex')).
 */

import { supabase } from '@/integrations/supabase/client'

// ─── Types ────────────────────────────────────────────────────────────────────

export type McpTokenScope = 'workspace' | 'organization'

export interface McpToken {
  id: string
  user_id: string
  org_id: string | null
  workspace_id: string | null
  name: string
  token: string
  scope: McpTokenScope
  last_used_at: string | null
  created_at: string
}

export interface CreateMcpTokenParams {
  name: string
  scope: McpTokenScope
  org_id: string
  /** Required when scope = 'workspace' */
  workspace_id?: string
}

// ─── Service functions ────────────────────────────────────────────────────────

/**
 * Fetch all MCP tokens for the authenticated user.
 * RLS on mcp_tokens restricts results to user_id = auth.uid().
 */
export async function getMcpTokens(): Promise<McpToken[]> {
  const { data, error } = await supabase
    .from('mcp_tokens')
    .select('id, user_id, org_id, workspace_id, name, token, scope, last_used_at, created_at')
    .order('created_at', { ascending: false })

  if (error) {
    throw new Error(`Failed to fetch MCP tokens: ${error.message}`)
  }

  return (data ?? []) as McpToken[]
}

/**
 * Create a new MCP token.
 * The token hex value is auto-generated by Postgres default.
 * Returns the full token row including the generated token value — surface it to the user once.
 */
export async function createMcpToken(params: CreateMcpTokenParams): Promise<McpToken> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const insert: Record<string, string | null> = {
    user_id: user.id,
    name: params.name.trim() || 'My MCP Token',
    scope: params.scope,
    org_id: params.org_id,
    workspace_id: params.scope === 'workspace' ? (params.workspace_id ?? null) : null,
  }

  const { data, error } = await supabase
    .from('mcp_tokens')
    .insert(insert)
    .select('id, user_id, org_id, workspace_id, name, token, scope, last_used_at, created_at')
    .single()

  if (error) {
    throw new Error(`Failed to create MCP token: ${error.message}`)
  }

  return data as McpToken
}

/**
 * Delete an MCP token by ID.
 * RLS ensures users can only delete their own tokens.
 */
export async function deleteMcpToken(id: string): Promise<void> {
  const { error } = await supabase
    .from('mcp_tokens')
    .delete()
    .eq('id', id)

  if (error) {
    throw new Error(`Failed to delete MCP token: ${error.message}`)
  }
}

/**
 * Build the full MCP server endpoint URL for a given token value.
 * The URL is pasted into Claude Desktop / Cursor / ChatGPT config.
 */
export function getMcpUrl(): string {
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string
  return `${supabaseUrl}/functions/v1/mcp-server`
}
