import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { ConnectorSetupCluster } from "../ConnectorSetupCluster";
import type {
  ConnectorAdapter,
  ConnectorSourceApp,
  ConnectorStatus,
} from "../../registry/types";

const toastError = vi.fn();
const toastSuccess = vi.fn();
const refresh = vi.fn();
const windowOpen = vi.fn();

function TestIcon({ className }: { className?: string }) {
  return <span className={className} data-testid="connector-icon" />;
}

const zoomGetOAuthAuthUrl = vi.fn();
const fathomGetOAuthAuthUrl = vi.fn();
const firefliesSaveApiKeyCredentials = vi.fn();
const firefliesGetWebhookDetails = vi.fn();
const firefliesGetWebhookVerification = vi.fn();
const firefliesDisconnect = vi.fn();
const plaudSaveApiKeyCredentials = vi.fn();
const readAiGetOAuthAuthUrl = vi.fn();
const readAiSaveApiKeyCredentials = vi.fn();
const readAiGetWebhookDetails = vi.fn();
const readAiSaveWebhookConfig = vi.fn();
const readAiGetWebhookVerification = vi.fn();

const adapters: Record<ConnectorSourceApp, ConnectorAdapter> = {
  zoom: {
    metadata: {
      sourceApp: "zoom",
      label: "Zoom",
      description: "Cloud recordings",
      icon: TestIcon,
      authMethods: ["oauth"],
      order: 1,
    },
    setup: {
      kind: "oauth",
      helperCopy: {
        disconnected: "Connect Zoom to import cloud recordings.",
        connected: "Zoom is connected.",
      },
    },
    getOAuthAuthUrl: zoomGetOAuthAuthUrl,
  },
  fireflies: {
    metadata: {
      sourceApp: "fireflies",
      label: "Fireflies",
      description: "Transcript API import",
      icon: TestIcon,
      authMethods: ["api_key", "webhook_only"],
      order: 2,
    },
    setup: {
      kind: "api_key_webhook",
      credentialFields: [
        {
          name: "apiKey",
          label: "Fireflies API key",
          required: true,
          secret: true,
          placeholder: "Your Fireflies API key",
        },
      ],
      webhook: {
        required: true,
        providerLabel: "Fireflies",
        urlLabel: "Webhook URL for Fireflies",
        signingSecretLabel: "Webhook signing secret",
        signingSecretField: "webhookSecret",
        destinationPath: "fireflies-webhook",
        verification: {
          required: true,
          lastVerifiedAtField: "lastVerifiedAt",
          lastMessageField: "lastMessage",
        },
      },
      helperCopy: {
        disconnected: "Paste a Fireflies API key.",
        saveSuccess: "Fireflies settings saved.",
      },
    },
    saveApiKeyCredentials: firefliesSaveApiKeyCredentials,
    getWebhookDetails: firefliesGetWebhookDetails,
    getWebhookVerification: firefliesGetWebhookVerification,
    disconnect: firefliesDisconnect,
  },
  fathom: {
    metadata: {
      sourceApp: "fathom",
      label: "Fathom",
      description: "AI meeting recorder",
      icon: TestIcon,
      authMethods: ["oauth"],
      order: 3,
    },
    setup: {
      kind: "oauth",
      supportsMultipleAccounts: true,
      helperCopy: {
        disconnected: "Connect Fathom.",
        connected: "Fathom is connected.",
      },
    },
    getOAuthAuthUrl: fathomGetOAuthAuthUrl,
  },
  plaud: {
    metadata: {
      sourceApp: "plaud",
      label: "Plaud",
      description: "AI voice recorder",
      icon: TestIcon,
      authMethods: ["api_key"],
      order: 4,
      badge: "beta",
    },
    setup: {
      kind: "browser_bridge",
      beta: true,
      credentialFields: [
        {
          name: "apiKey",
          label: "Plaud Web token",
          required: true,
          secret: true,
          placeholder: "Paste the Plaud Bearer token from Plaud Web",
        },
        {
          name: "apiBase",
          label: "Plaud region",
          required: true,
          placeholder: "https://api.plaud.ai",
          options: [
            { label: "Global", value: "https://api.plaud.ai" },
          ],
        },
      ],
      helperCopy: {
        disconnected: "Use the CallVault Plaud Connector browser bridge.",
      },
    },
    saveApiKeyCredentials: plaudSaveApiKeyCredentials,
  },
  "read-ai": {
    metadata: {
      sourceApp: "read-ai",
      label: "Read.ai",
      description: "Meeting reports",
      icon: TestIcon,
      authMethods: ["oauth", "api_key"],
      order: 5,
      badge: "beta",
    },
    setup: {
      kind: "oauth",
      alternateKinds: ["api_key"],
      credentialFields: [
        {
          name: "apiKey",
          label: "Read.ai bearer token",
          required: true,
          secret: true,
          placeholder: "Paste a Read.ai bearer token",
        },
      ],
      helperCopy: {
        disconnected: "Connect Read.ai with OAuth, or paste a bearer token.",
        saveSuccess: "Read.ai credentials saved.",
        verificationWaiting: "Paste the signing key generated by Read.ai.",
      },
      webhook: {
        providerLabel: "Read.ai",
        urlLabel: "Webhook URL",
        signingSecretLabel: "Read.ai signing key",
        signingSecretField: "webhookSecret",
        destinationPath: "read-ai-webhook",
        pathTokenField: "webhookPathToken",
        verification: {
          lastVerifiedAtField: "lastVerifiedAt",
          lastMessageField: "lastMessage",
        },
      },
    },
    getOAuthAuthUrl: readAiGetOAuthAuthUrl,
    saveApiKeyCredentials: readAiSaveApiKeyCredentials,
    getWebhookDetails: readAiGetWebhookDetails,
    saveWebhookConfig: readAiSaveWebhookConfig,
    getWebhookVerification: readAiGetWebhookVerification,
  },
  grain: mockNoAuthAdapter("grain", "Grain", 6),
  youtube: mockNoAuthAdapter("youtube", "YouTube", 5),
  "file-upload": mockNoAuthAdapter("file-upload", "File Upload", 7),
};

let currentStatus: ConnectorStatus | null = null;
let currentLoading = false;

vi.mock("sonner", () => ({
  toast: {
    error: (...args: unknown[]) => toastError(...args),
    success: (...args: unknown[]) => toastSuccess(...args),
  },
}));

vi.mock("../../hooks/useConnector", () => ({
  useConnector: (sourceApp: ConnectorSourceApp) => ({
    status: currentStatus ?? makeStatus(sourceApp, false),
    isLoading: currentLoading,
    error: null,
    refresh,
  }),
}));

vi.mock("../../registry/connectorRegistry", () => ({
  getConnectorAdapter: (sourceApp: ConnectorSourceApp) => adapters[sourceApp],
}));

vi.mock("@/components/import/DefaultDestinationBar", () => ({
  DefaultDestinationBar: () => (
    <div data-testid="default-destination-bar">Destination</div>
  ),
}));

describe("ConnectorSetupCluster", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    currentLoading = false;
    currentStatus = null;
    zoomGetOAuthAuthUrl.mockResolvedValue({
      authUrl: "https://zoom.example/oauth",
      sourceId: "src_zoom",
    });
    fathomGetOAuthAuthUrl.mockResolvedValue({
      authUrl: "https://fathom.example/oauth",
      sourceId: "src_fathom_new",
    });
    readAiGetOAuthAuthUrl.mockResolvedValue({
      authUrl: "https://read.example/oauth",
      sourceId: "src_read_ai",
    });
    readAiSaveApiKeyCredentials.mockResolvedValue({
      sourceId: "src_read_ai",
    });
    readAiGetWebhookDetails.mockResolvedValue({
      webhookUrl: "https://app.callvaultai.com/api/read-ai-webhook/rwh_saved",
      webhookPathToken: "rwh_saved",
      webhookSigningSecret: null,
      verification: {
        verified: false,
        lastVerifiedAt: null,
        lastMessage: null,
      },
    });
    readAiSaveWebhookConfig.mockResolvedValue({
      sourceId: "src_read_ai",
      webhookUrl: "https://app.callvaultai.com/api/read-ai-webhook/rwh_saved",
      webhookPathToken: "rwh_saved",
      webhookSigningSecret: "read-signing-key",
      verification: {
        verified: false,
        lastVerifiedAt: null,
        lastMessage: null,
      },
    });
    readAiGetWebhookVerification.mockResolvedValue({
      verified: false,
      lastVerifiedAt: null,
      lastMessage: null,
    });
    firefliesSaveApiKeyCredentials.mockResolvedValue({
      sourceId: "src_fireflies",
      webhookSigningSecret: "generated-secret",
      webhookPathToken: "ffwh_123",
    });
    firefliesGetWebhookDetails.mockResolvedValue({
      webhookSigningSecret: "saved-secret",
      webhookPathToken: "ffwh_saved",
      verification: {
        verified: true,
        lastVerifiedAt: "2026-05-25T12:00:00Z",
        lastMessage: "Fireflies webhook received",
      },
    });
    firefliesGetWebhookVerification.mockResolvedValue({
      verified: true,
      lastVerifiedAt: new Date().toISOString(),
      lastMessage: "Fireflies webhook received",
    });
    Object.defineProperty(window, "open", {
      configurable: true,
      value: windowOpen,
    });
  });

  it("starts OAuth setup through the adapter", async () => {
    render(<ConnectorSetupCluster sourceApp="zoom" mode="settings" />);

    fireEvent.click(screen.getByRole("button", { name: /connect zoom/i }));

    await waitFor(() => expect(zoomGetOAuthAuthUrl).toHaveBeenCalled());
    expect(windowOpen).toHaveBeenCalledWith(
      "https://zoom.example/oauth",
      "_blank",
      "noopener,noreferrer",
    );
  });

  it("shows a separate add-account action for connected multi-account Fathom", async () => {
    currentStatus = makeStatus("fathom", true, {
      sourceId: "src_fathom_existing",
      accountEmail: "first@example.com",
    });

    render(<ConnectorSetupCluster sourceApp="fathom" mode="import" />);

    fireEvent.click(
      screen.getByRole("button", { name: /add fathom account/i }),
    );

    await waitFor(() => expect(fathomGetOAuthAuthUrl).toHaveBeenCalledWith({
      sourceId: undefined,
    }));
    expect(windowOpen).toHaveBeenCalledWith(
      "https://fathom.example/oauth",
      "_blank",
      "noopener,noreferrer",
    );
  });

  it("passes the current Fathom source id when reconnecting", async () => {
    currentStatus = makeStatus("fathom", true, {
      sourceId: "src_fathom_existing",
      accountEmail: "first@example.com",
    });

    render(<ConnectorSetupCluster sourceApp="fathom" mode="import" />);

    fireEvent.click(screen.getByRole("button", { name: /^reconnect$/i }));

    await waitFor(() => expect(fathomGetOAuthAuthUrl).toHaveBeenCalledWith({
      sourceId: "src_fathom_existing",
    }));
  });

  it("saves API-key webhook credentials through the adapter", async () => {
    const onSaved = vi.fn();
    render(
      <ConnectorSetupCluster
        sourceApp="fireflies"
        mode="import"
        onSaved={onSaved}
      />,
    );

    fireEvent.change(screen.getByLabelText("Fireflies API key"), {
      target: { value: "ff-api-key" },
    });

    fireEvent.click(screen.getByRole("button", { name: /save connection/i }));

    await waitFor(() =>
      expect(firefliesSaveApiKeyCredentials).toHaveBeenCalledWith(
        expect.objectContaining({ apiKey: "ff-api-key" }),
      ),
    );
    expect(onSaved).toHaveBeenCalledWith("src_fireflies");
    expect(toastSuccess).toHaveBeenCalledWith("Fireflies settings saved.");
  });

  it("shows alternate API-key setup for OAuth connectors that support token fallback", async () => {
    const onSaved = vi.fn();
    render(
      <ConnectorSetupCluster
        sourceApp="read-ai"
        mode="settings"
        onSaved={onSaved}
      />,
    );

    expect(
      screen.getByRole("button", { name: /connect read\.ai/i }),
    ).toBeInTheDocument();

    fireEvent.change(screen.getByLabelText("Read.ai bearer token"), {
      target: { value: "read-token" },
    });

    fireEvent.click(screen.getByRole("button", { name: /save connection/i }));

    await waitFor(() =>
      expect(readAiSaveApiKeyCredentials).toHaveBeenCalledWith(
        expect.objectContaining({ apiKey: "read-token" }),
      ),
    );
    expect(onSaved).toHaveBeenCalledWith("src_read_ai");
    expect(toastSuccess).toHaveBeenCalledWith("Read.ai credentials saved.");
  });

  it("passes the existing source id when reconnecting token fallback credentials", async () => {
    currentStatus = makeStatus("read-ai", true, {
      sourceId: "src_read_ai_existing",
    });

    render(<ConnectorSetupCluster sourceApp="read-ai" mode="settings" />);

    fireEvent.click(screen.getAllByRole("button", { name: /reconnect/i })[1]);
    fireEvent.change(screen.getByLabelText("Read.ai bearer token"), {
      target: { value: "new-read-token" },
    });
    fireEvent.click(screen.getByRole("button", { name: /save changes/i }));

    await waitFor(() =>
      expect(readAiSaveApiKeyCredentials).toHaveBeenCalledWith(
        expect.objectContaining({
          sourceId: "src_read_ai_existing",
          apiKey: "new-read-token",
        }),
      ),
    );
  });

  it("saves connected OAuth connector webhook settings separately from token credentials", async () => {
    currentStatus = makeStatus("read-ai", true, {
      sourceId: "src_read_ai",
      accountEmail: "andrew@aisimple.co",
    });

    render(<ConnectorSetupCluster sourceApp="read-ai" mode="settings" />);

    await waitFor(() =>
      expect(readAiGetWebhookDetails).toHaveBeenCalledWith({
        sourceId: "src_read_ai",
      }),
    );

    fireEvent.change(screen.getByLabelText("Read.ai signing key"), {
      target: { value: "read-signing-key" },
    });
    fireEvent.click(
      screen.getByRole("button", { name: /save webhook settings/i }),
    );

    await waitFor(() =>
      expect(readAiSaveWebhookConfig).toHaveBeenCalledWith(
        expect.objectContaining({
          sourceId: "src_read_ai",
          webhookSigningSecret: "read-signing-key",
        }),
      ),
    );
    expect(readAiSaveApiKeyCredentials).not.toHaveBeenCalled();
  });

  it("loads connected webhook details and shows verification state", async () => {
    currentStatus = makeStatus("fireflies", true, {
      sourceId: "src_fireflies",
      accountEmail: "owner@example.com",
    });

    render(<ConnectorSetupCluster sourceApp="fireflies" mode="settings" />);

    await waitFor(() =>
      expect(firefliesGetWebhookDetails).toHaveBeenCalledWith({
        sourceId: "src_fireflies",
      }),
    );

    fireEvent.click(screen.getByRole("button", { name: /reconnect/i }));

    expect(
      screen.getByDisplayValue(/fireflies-webhook\/ffwh_saved$/),
    ).toBeInTheDocument();
    expect(screen.getAllByText("Verified").length).toBeGreaterThan(0);
  });

  it("renders one primary Plaud bridge connect button", () => {
    render(<ConnectorSetupCluster sourceApp="plaud" mode="settings" />);

    expect(
      screen.getByRole("button", { name: /^connect plaud$/i }),
    ).toBeInTheDocument();
    expect(
      screen.getByRole("link", { name: /open plaud web only/i }),
    ).toBeInTheDocument();
  });
});

function makeStatus(
  sourceApp: ConnectorSourceApp,
  connected: boolean,
  overrides: Partial<ConnectorStatus> = {},
): ConnectorStatus {
  return {
    sourceApp,
    connected,
    hasEverConnected: connected,
    accountEmail: null,
    lastSyncAt: null,
    tokenExpiresMs: null,
    tokenExpired: false,
    errorMessage: null,
    sourceId: connected ? `src_${sourceApp}` : null,
    allRows: [],
    ...overrides,
  };
}

function mockNoAuthAdapter(
  sourceApp: ConnectorSourceApp,
  label: string,
  order: number,
): ConnectorAdapter {
  return {
    metadata: {
      sourceApp,
      label,
      description: `${label} setup`,
      icon: TestIcon,
      authMethods: ["none"],
      order,
    },
    setup: {
      kind: "none",
    },
  };
}
