#!/bin/bash

# Auto-Build Environment Setup
# Component Deduplication & Reusability Audit
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECKS
# ============================================

echo ""
echo "Checking environment..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js.${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js:${NC} $(node --version)"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install npm.${NC}"
    exit 1
fi
echo -e "${GREEN}npm:${NC} $(npm --version)"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting frontend development server..."

# Start Vite dev server
npm run dev &
VITE_PID=$!

# Wait for Vite to be ready
wait_for_service 3000 "Frontend (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Development Commands:"
echo "  TypeScript Check: npx tsc --noEmit"
echo "  Run Tests:        npx vitest run"
echo "  Build:            npx vite build"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

# Keep script running
wait $VITE_PID
