-- Reconciliation placeholder for an ORPHANED remote migration version.
--
-- Version 20260625120000 is recorded as applied in the PRODUCTION
-- supabase_migrations.schema_migrations history, but no source file exists in
-- this repo. Like 20260623120000, it was applied by a prior autopilot
-- self-resolution attempt for ticket 27aeb6cb whose migration file was
-- discarded with its ephemeral GSD worktree.
--
-- Effect of the drift: `supabase db push` aborts at preflight with
--   "Remote migration versions not found in local migrations directory"
-- blocking EVERY autopilot migration deploy to prod.
--
-- This no-op file restores local↔remote parity so pushes succeed again. The
-- version is already marked applied remotely, so `db push` skips this body and
-- never executes it. It exists purely to satisfy the history preflight.
SELECT 1;
