-- Migration: Create hooks table for storing Agent 3 (Hook Generator) output
-- Purpose: Store generated hooks from insights for content generation pipeline
-- Author: Claude Code
-- Date: 2026-01-11

-- ============================================================================
-- TABLE: hooks
-- ============================================================================
-- Stores hooks generated by Agent 3 (Hook Generator) from extracted insights
-- User-facing library - hooks can be starred, selected, and used for content generation
CREATE TABLE IF NOT EXISTS public.hooks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  recording_id BIGINT,

  -- Hook content
  hook_text TEXT NOT NULL,

  -- Related insights (array of insight UUIDs)
  insight_ids UUID[] DEFAULT '{}',

  -- Classification fields (from Agent 3 output)
  emotion_category TEXT CHECK (emotion_category IS NULL OR emotion_category IN (
    'anger_outrage',
    'awe_surprise',
    'social_currency',
    'relatable',
    'practical_value',
    'humor_sharp',
    'neutral'
  )),
  virality_score INTEGER CHECK (virality_score IS NULL OR (virality_score >= 1 AND virality_score <= 5)),
  topic_hint TEXT,

  -- User actions
  is_starred BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'generated' CHECK (status IN ('generated', 'selected', 'archived')),

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints for reasonable content limits
  CONSTRAINT hooks_hook_text_length CHECK (char_length(hook_text) <= 2000),
  CONSTRAINT hooks_topic_hint_length CHECK (topic_hint IS NULL OR char_length(topic_hint) <= 500),

  -- Composite foreign key to fathom_calls (optional - hooks can exist without recording)
  CONSTRAINT hooks_fathom_call_fkey
    FOREIGN KEY (recording_id, user_id)
    REFERENCES public.fathom_calls(recording_id, user_id)
    ON DELETE SET NULL
    DEFERRABLE INITIALLY DEFERRED
);

-- ============================================================================
-- INDEXES
-- ============================================================================
-- Performance indexes for common query patterns

-- Index for looking up hooks by user
CREATE INDEX IF NOT EXISTS idx_hooks_user_id
  ON public.hooks(user_id);

-- Index for looking up hooks by recording
CREATE INDEX IF NOT EXISTS idx_hooks_recording_id
  ON public.hooks(recording_id) WHERE recording_id IS NOT NULL;

-- Index for filtering by emotion category
CREATE INDEX IF NOT EXISTS idx_hooks_emotion_category
  ON public.hooks(emotion_category) WHERE emotion_category IS NOT NULL;

-- Index for filtering by virality score
CREATE INDEX IF NOT EXISTS idx_hooks_virality_score
  ON public.hooks(virality_score DESC) WHERE virality_score IS NOT NULL;

-- Index for filtering starred hooks
CREATE INDEX IF NOT EXISTS idx_hooks_is_starred
  ON public.hooks(user_id, is_starred) WHERE is_starred = TRUE;

-- Index for filtering by status
CREATE INDEX IF NOT EXISTS idx_hooks_status
  ON public.hooks(status);

-- Index for sorting by creation date (most recent first)
CREATE INDEX IF NOT EXISTS idx_hooks_created_at
  ON public.hooks(created_at DESC);

-- Composite index for efficient user + status + starred lookups
CREATE INDEX IF NOT EXISTS idx_hooks_user_status_starred
  ON public.hooks(user_id, status, is_starred);

-- ============================================================================
-- TRIGGERS
-- ============================================================================
-- Automatically update the updated_at timestamp

-- Apply trigger to hooks table (reuses existing function)
DROP TRIGGER IF EXISTS update_hooks_updated_at ON public.hooks;
CREATE TRIGGER update_hooks_updated_at
  BEFORE UPDATE ON public.hooks
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on hooks table
ALTER TABLE public.hooks ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- RLS POLICIES: hooks
-- ============================================================================

-- Policy: Users can view their own hooks
CREATE POLICY "Users can view their own hooks"
  ON public.hooks
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can insert their own hooks
CREATE POLICY "Users can insert their own hooks"
  ON public.hooks
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own hooks
CREATE POLICY "Users can update their own hooks"
  ON public.hooks
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own hooks
CREATE POLICY "Users can delete their own hooks"
  ON public.hooks
  FOR DELETE
  USING (auth.uid() = user_id);

-- Policy: Service role can manage all hooks (for edge functions)
CREATE POLICY "Service role can manage hooks"
  ON public.hooks
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================================
-- PERMISSIONS
-- ============================================================================
-- Grant permissions to authenticated users
GRANT ALL ON public.hooks TO authenticated;

-- ============================================================================
-- COMMENTS
-- ============================================================================
-- Add helpful comments to table and columns

COMMENT ON TABLE public.hooks IS
  'Stores hooks generated by Agent 3 (Hook Generator). User-facing library for content generation.';

COMMENT ON COLUMN public.hooks.user_id IS
  'User who owns this hook';

COMMENT ON COLUMN public.hooks.recording_id IS
  'Reference to the fathom_calls recording this hook was generated from (optional)';

COMMENT ON COLUMN public.hooks.hook_text IS
  'The generated hook text ready for content creation (max 2,000 chars)';

COMMENT ON COLUMN public.hooks.insight_ids IS
  'Array of insight UUIDs that this hook was generated from';

COMMENT ON COLUMN public.hooks.emotion_category IS
  'Emotional category: anger_outrage, awe_surprise, social_currency, relatable, practical_value, humor_sharp, or neutral';

COMMENT ON COLUMN public.hooks.virality_score IS
  'Predicted virality potential from 1-5, where 5 is most likely to resonate';

COMMENT ON COLUMN public.hooks.topic_hint IS
  'Topic or theme hint for organizing and filtering hooks (max 500 chars)';

COMMENT ON COLUMN public.hooks.is_starred IS
  'Whether the user has starred/favorited this hook';

COMMENT ON COLUMN public.hooks.status IS
  'Hook status: generated (new), selected (used for content), or archived';

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
