-- Migration: Create content_items table for storing Agent 4 (Content Builder) output
-- Purpose: Store generated posts and emails from hooks for the content library
-- Author: Claude Code
-- Date: 2026-01-11

-- ============================================================================
-- TABLE: content_items
-- ============================================================================
-- Stores content generated by Agent 4 (Content Builder) - social posts and emails
-- User-facing library - content can be edited, marked as used, and copied
CREATE TABLE IF NOT EXISTS public.content_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  hook_id UUID REFERENCES public.hooks(id) ON DELETE SET NULL,

  -- Content type and text
  content_type TEXT NOT NULL CHECK (content_type IN ('post', 'email')),
  content_text TEXT NOT NULL,

  -- Email-specific fields (null for posts)
  email_subject TEXT,

  -- Status tracking
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'used')),
  used_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints for reasonable content limits
  CONSTRAINT content_items_content_text_length CHECK (char_length(content_text) <= 10000),
  CONSTRAINT content_items_email_subject_length CHECK (email_subject IS NULL OR char_length(email_subject) <= 500),

  -- Ensure email_subject is only set for emails
  CONSTRAINT content_items_email_subject_type CHECK (
    (content_type = 'post' AND email_subject IS NULL) OR
    (content_type = 'email')
  ),

  -- Ensure used_at is set when status is 'used'
  CONSTRAINT content_items_used_at_status CHECK (
    (status = 'draft' AND used_at IS NULL) OR
    (status = 'used')
  )
);

-- ============================================================================
-- INDEXES
-- ============================================================================
-- Performance indexes for common query patterns

-- Index for looking up content by user
CREATE INDEX IF NOT EXISTS idx_content_items_user_id
  ON public.content_items(user_id);

-- Index for looking up content by hook
CREATE INDEX IF NOT EXISTS idx_content_items_hook_id
  ON public.content_items(hook_id) WHERE hook_id IS NOT NULL;

-- Index for filtering by content type
CREATE INDEX IF NOT EXISTS idx_content_items_content_type
  ON public.content_items(content_type);

-- Index for filtering by status
CREATE INDEX IF NOT EXISTS idx_content_items_status
  ON public.content_items(status);

-- Composite index for efficient user + type queries (most common)
CREATE INDEX IF NOT EXISTS idx_content_items_user_type
  ON public.content_items(user_id, content_type);

-- Composite index for efficient user + type + status queries
CREATE INDEX IF NOT EXISTS idx_content_items_user_type_status
  ON public.content_items(user_id, content_type, status);

-- Index for sorting by creation date (most recent first)
CREATE INDEX IF NOT EXISTS idx_content_items_created_at
  ON public.content_items(created_at DESC);

-- Index for sorting by used_at (most recently used first)
CREATE INDEX IF NOT EXISTS idx_content_items_used_at
  ON public.content_items(used_at DESC) WHERE used_at IS NOT NULL;

-- ============================================================================
-- TRIGGERS
-- ============================================================================
-- Automatically update the updated_at timestamp

-- Apply trigger to content_items table (reuses existing function)
DROP TRIGGER IF EXISTS update_content_items_updated_at ON public.content_items;
CREATE TRIGGER update_content_items_updated_at
  BEFORE UPDATE ON public.content_items
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- FUNCTION: Auto-set used_at when status changes to 'used'
-- ============================================================================
CREATE OR REPLACE FUNCTION set_content_items_used_at()
RETURNS TRIGGER AS $$
BEGIN
  -- Set used_at when status changes to 'used'
  IF NEW.status = 'used' AND (OLD.status IS NULL OR OLD.status != 'used') THEN
    NEW.used_at = NOW();
  END IF;

  -- Clear used_at when status changes away from 'used'
  IF NEW.status = 'draft' AND OLD.status = 'used' THEN
    NEW.used_at = NULL;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to auto-set used_at
DROP TRIGGER IF EXISTS set_content_items_used_at_trigger ON public.content_items;
CREATE TRIGGER set_content_items_used_at_trigger
  BEFORE UPDATE ON public.content_items
  FOR EACH ROW
  EXECUTE FUNCTION set_content_items_used_at();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on content_items table
ALTER TABLE public.content_items ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- RLS POLICIES: content_items
-- ============================================================================

-- Policy: Users can view their own content items
CREATE POLICY "Users can view their own content items"
  ON public.content_items
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can insert their own content items
CREATE POLICY "Users can insert their own content items"
  ON public.content_items
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own content items
CREATE POLICY "Users can update their own content items"
  ON public.content_items
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own content items
CREATE POLICY "Users can delete their own content items"
  ON public.content_items
  FOR DELETE
  USING (auth.uid() = user_id);

-- Policy: Service role can manage all content items (for edge functions)
CREATE POLICY "Service role can manage content items"
  ON public.content_items
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================================
-- PERMISSIONS
-- ============================================================================
-- Grant permissions to authenticated users
GRANT ALL ON public.content_items TO authenticated;

-- ============================================================================
-- COMMENTS
-- ============================================================================
-- Add helpful comments to table and columns

COMMENT ON TABLE public.content_items IS
  'Stores content generated by Agent 4 (Content Builder) - social posts and emails. User-facing library.';

COMMENT ON COLUMN public.content_items.user_id IS
  'User who owns this content item';

COMMENT ON COLUMN public.content_items.hook_id IS
  'Reference to the hook this content was generated from (optional)';

COMMENT ON COLUMN public.content_items.content_type IS
  'Type of content: post (social media) or email';

COMMENT ON COLUMN public.content_items.content_text IS
  'The main content text - post body or email body (max 10,000 chars)';

COMMENT ON COLUMN public.content_items.email_subject IS
  'Email subject line - only set for content_type=email (max 500 chars)';

COMMENT ON COLUMN public.content_items.status IS
  'Content status: draft (not yet used) or used (published/sent)';

COMMENT ON COLUMN public.content_items.used_at IS
  'Timestamp when content was marked as used - auto-set by trigger';

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
