import { RiCloudLine } from "@remixicon/react";
import { disconnectConnectorSource } from "../../hooks/useConnector";
import {
  createDateRangeSearch,
  createOAuthUrlGetter,
  createSelectedImporter,
  createTokenCredentialSaver,
  invokeConnectorFunction,
  wasAlreadySynced,
} from "./adapter-helpers";
import type { ConnectorAdapter } from "../types";

interface ReadAiAvailableMeeting {
  recording_id: string;
  title: string;
  recording_start_time: string | null;
  duration: number | null;
  calendar_invitees?: Array<{ name: string | null; email: string | null }>;
  synced: boolean;
  importable?: boolean;
  share_url?: string | null;
  source_url?: string | null;
}

export const readAiAdapter: ConnectorAdapter = {
  metadata: {
    sourceApp: "read-ai",
    label: "Read.ai",
    description: "Meeting reports and transcripts",
    icon: RiCloudLine,
    brandColor: "#5B7CFA",
    authMethods: ["oauth", "api_key"],
    order: 45,
    badge: "beta",
  },
  setup: {
    kind: "oauth",
    alternateKinds: ["api_key"],
    accountLabelField: "email",
    credentialFields: [
      {
        name: "apiKey",
        label: "Read.ai bearer token",
        required: true,
        secret: true,
        placeholder: "Paste a Read.ai bearer token",
        autoComplete: "off",
      },
    ],
    helperCopy: {
      disconnected:
        "Connect Read.ai with OAuth, or paste a bearer token while the connector is in beta.",
      connected: "Read.ai is connected and ready to import meeting reports.",
      saveSuccess: "Read.ai credentials saved.",
      verificationWaiting:
        "Create a Read.ai webhook with the URL below, paste the signing key Read.ai shows after creation, then send a test request.",
    },
    webhook: {
      required: false,
      providerLabel: "Read.ai",
      urlLabel: "Webhook URL",
      signingSecretLabel: "Read.ai signing key",
      signingSecretPlaceholder: "Paste the signing key generated by Read.ai",
      signingSecretField: "webhookSecret",
      destinationPath: "read-ai-webhook",
      pathTokenField: "webhookPathToken",
      verification: {
        lastVerifiedAtField: "lastVerifiedAt",
        lastMessageField: "lastMessage",
      },
      eventTypes: ["meeting_end", "manual"],
      helperText:
        "Read.ai webhooks are configured in Read.ai Integrations. Use HTTPS, then paste the signing key Read.ai generates so CallVault can verify X-Read-Signature.",
    },
  },

  getOAuthAuthUrl: createOAuthUrlGetter("read-ai-oauth-url"),

  saveApiKeyCredentials: createTokenCredentialSaver("read-ai-connect-token"),

  async disconnect(sourceId) {
    await disconnectConnectorSource({ sourceApp: "read-ai", sourceId });
  },

  async getWebhookDetails({ sourceId }) {
    return await invokeConnectorFunction("read-ai-webhook-settings", {
      body: { sourceId },
    });
  },

  async saveWebhookConfig({ sourceId, webhookSigningSecret }) {
    const data = await invokeConnectorFunction<{
      sourceId?: string;
      webhookUrl?: string;
      webhookPathToken?: string | null;
      webhookSigningSecret?: string | null;
      verification?: { verified: boolean; lastVerifiedAt: string | null; lastMessage?: string | null };
    } | null>("read-ai-webhook-settings", {
      body: { sourceId, webhookSigningSecret },
    });

    if (!data?.sourceId) {
      throw new Error("read-ai-webhook-settings returned no sourceId");
    }

    return {
      sourceId: data.sourceId,
      webhookUrl: data.webhookUrl,
      webhookPathToken: data.webhookPathToken,
      webhookSigningSecret: data.webhookSigningSecret,
      verification: data.verification ?? null,
    };
  },

  async getWebhookVerification({ sourceId }) {
    const details = await this.getWebhookDetails?.({ sourceId });
    return (
      details?.verification ?? {
        verified: false,
        lastVerifiedAt: null,
      }
    );
  },

  searchAvailable: createDateRangeSearch<ReadAiAvailableMeeting>({
    functionName: "read-ai-fetch-meetings",
    resultKey: "meetings",
    defaultLimit: 10,
    mapItem: (meeting) => ({
      externalId: meeting.recording_id,
      title: meeting.title,
      startTime: meeting.recording_start_time,
      durationSeconds: meeting.duration,
      participants: meeting.calendar_invitees,
      alreadyImported: wasAlreadySynced(meeting),
      externalUrl: meeting.share_url ?? meeting.source_url,
      metadata: { importable: meeting.importable ?? true },
    }),
  }),

  importSelected: createSelectedImporter({
    functionName: "read-ai-sync-meetings",
    idsField: "meetingIds",
    messageLabel: "Read.ai",
    messageNoun: "call",
  }),
};
